## Data Cleaning
Tujuan: Membersihkan dan menyiapkan data sebelum digunakan.

## 1. Loading

Pertama, kita perlu mengambil data.

In [37]:
import pandas as pd

In [38]:
results = pd.read_csv("../data/raw/results.csv")
former_names = pd.read_csv("../data/raw/former_names.csv")
goalscorers = pd.read_csv("../data/raw/goalscorers.csv")
shootouts = pd.read_csv("../data/raw/shootouts.csv")

## 2. Informasi Umum Data

Kemudian, kita akan melihat beberapa informasi umum dari tabel data.

### 2.1 Tabel Results

Kita akan mengecek tabel `results`.

In [39]:
# BENTUK TABEL
results.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False


In [40]:
# INFORMASI UMUM
results.info()

<class 'pandas.DataFrame'>
RangeIndex: 49477 entries, 0 to 49476
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   date        49477 non-null  str    
 1   home_team   49477 non-null  str    
 2   away_team   49477 non-null  str    
 3   home_score  49433 non-null  float64
 4   away_score  49433 non-null  float64
 5   tournament  49477 non-null  str    
 6   city        49477 non-null  str    
 7   country     49477 non-null  str    
 8   neutral     49477 non-null  bool   
dtypes: bool(1), float64(2), str(6)
memory usage: 3.1 MB


Tipe data terlihat normal selain kolom `date`. Kolom `date` masih mempunyai format string, sehingga harus diubah nanti.

In [41]:
# MISSING VALUE
results.isna().sum()

date           0
home_team      0
away_team      0
home_score    44
away_score    44
tournament     0
city           0
country        0
neutral        0
dtype: int64

Tampaknya terdapat data kosong dengan rincian berikut:
- `home_score` : 44 data kosong
- `away_score` : 44 data kosong

In [42]:
# DUPLIKAT
results.duplicated().sum()

np.int64(0)

### 2.2 Tabel Former Names

In [43]:
# BENTUK TABEL
former_names.head()

,current,former,start_date,end_date
0,Benin,Dahomey,1959-11-08,1975-11-30
1,Burkina Faso,Upper Volta,1960-04-14,1984-08-04
2,Curaçao,Netherlands Antilles,1957-03-03,2010-10-10
3,Czechoslovakia,Bohemia,1903-04-05,1919-01-01
4,Czechoslovakia,Bohemia and Moravia,1939-01-01,1945-05-01


In [44]:
# INFORMASI UMUM
former_names.info()

<class 'pandas.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   current     36 non-null     str  
 1   former      36 non-null     str  
 2   start_date  36 non-null     str  
 3   end_date    36 non-null     str  
dtypes: str(4)
memory usage: 1.3 KB


Kasus yang sama dengan tabel `results`, tabel ini memiliki tanggal (`start_date` dan `end_date`) dengan tipe string.

In [45]:
# MISSING VALUE
former_names.isna().sum()

current       0
former        0
start_date    0
end_date      0
dtype: int64

Tidak ada data kosong.

In [46]:
# DUPLIKAT
former_names.duplicated().sum()

np.int64(0)

Tidak ada data duplikat.

### 2.3 Tabel Goalscorers

In [47]:
# BENTUK TABEL
goalscorers.head()

,date,home_team,away_team,team,scorer,minute,own_goal,penalty
0,1916-07-02,Chile,Uruguay,Uruguay,José Piendibene,44.0,False,False
1,1916-07-02,Chile,Uruguay,Uruguay,Isabelino Gradín,55.0,False,False
2,1916-07-02,Chile,Uruguay,Uruguay,Isabelino Gradín,70.0,False,False
3,1916-07-02,Chile,Uruguay,Uruguay,José Piendibene,75.0,False,False
4,1916-07-06,Argentina,Chile,Argentina,Alberto Ohaco,2.0,False,False


In [48]:
# INFORMASI UMUM
goalscorers.info()

<class 'pandas.DataFrame'>
RangeIndex: 47690 entries, 0 to 47689
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   date       47690 non-null  str    
 1   home_team  47690 non-null  str    
 2   away_team  47690 non-null  str    
 3   team       47690 non-null  str    
 4   scorer     47642 non-null  str    
 5   minute     47434 non-null  float64
 6   own_goal   47690 non-null  bool   
 7   penalty    47690 non-null  bool   
dtypes: bool(2), float64(1), str(5)
memory usage: 2.3 MB


Masih dengan kasus yang sama dengan tabel `results`, tabel ini memiliki kolom `date` dengan tipe string.

In [49]:
# MISSING VALUE
goalscorers.isna().sum()

date           0
home_team      0
away_team      0
team           0
scorer        48
minute       256
own_goal       0
penalty        0
dtype: int64

Sepertinya terdapat banyak data kosong pada beberapa kolom.
- `scorer` : 44 data kosong
- `minute` : 256 data kosong

In [50]:
# DUPLIKAT
goalscorers.duplicated().sum()

np.int64(82)

Ternyata terdapat 82 data duplikat pada tabel `goalscorers`.

### 2.4 Tabel Shootouts

In [51]:
# BENTUK TABEL
shootouts.head()

,date,home_team,away_team,winner,first_shooter
0,1967-08-22,India,Taiwan,Taiwan,NaN
1,1971-11-14,South Korea,Vietnam Republic,South Korea,NaN
2,1972-05-07,South Korea,Iraq,Iraq,NaN
3,1972-05-17,Thailand,South Korea,South Korea,NaN
4,1972-05-19,Thailand,Cambodia,Thailand,NaN


In [52]:
# INFORMASI UMUM
shootouts.info()

<class 'pandas.DataFrame'>
RangeIndex: 678 entries, 0 to 677
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           678 non-null    str  
 1   home_team      678 non-null    str  
 2   away_team      678 non-null    str  
 3   winner         678 non-null    str  
 4   first_shooter  256 non-null    str  
dtypes: str(5)
memory usage: 26.6 KB


Tabel ini juga memiliki kolom `date` dengan tipe string.

In [53]:
# MISSING VALUE
shootouts.isna().sum()

date               0
home_team          0
away_team          0
winner             0
first_shooter    422
dtype: int64

Terdapat 422 data kosong pada kolom `first_shooter`.

In [54]:
# DUPLIKAT
shootouts.duplicated().sum()

np.int64(0)

Tidak ada data duplikat.

### 2.5 Insight

Berdasarkan pengecekan informasi umum pada keempat tabel, berikut adalah rangkuman temuan yang perlu ditindaklanjuti pada tahap pembersihan data selanjutnya:

- **2.1 `results`**: Tipe data pada kolom `date` masih berupa string dan perlu dikonversi menjadi format *datetime*. Ditemukan data kosong (*missing values*) pada kolom `home_score` (44 baris) dan `away_score` (44 baris).
- **2.2 `former_names`**: Kolom `start_date` dan `end_date` masih berformat string dan perlu diubah menjadi *datetime*. Tabel ini sudah tergolong bersih karena tidak memiliki *missing value* maupun data duplikat.
- **2.3 `goalscorers`**: Tipe data kolom `date` perlu disesuaikan menjadi *datetime*. Terdapat ketidaklengkapan data dengan adanya 44 *missing values* pada kolom `scorer` dan 256 pada `minute`. Selain itu, ditemukan 82 baris data duplikat yang harus dibersihkan.
- **2.4 `shootouts`**: Kolom `date` masih berformat string. Terdapat jumlah *missing values* yang cukup signifikan pada kolom `first_shooter` (422 baris data kosong). Tidak ditemukan adanya duplikasi data pada tabel ini.

#### Action Items (Rencana Pembersihan Data):
1. **Konversi Tipe Data**: Mengubah tipe data menjadi `datetime` untuk semua kolom yang memuat informasi tanggal (`date`, `start_date`, `end_date`) di seluruh tabel.
2. **Penanganan *Missing Values***: Melakukan investigasi lebih lanjut untuk menentukan strategi yang tepat (apakah akan diimputasi/diisi atau di-*drop*/dihapus) pada kolom yang kosong di tabel `results`, `goalscorers`, dan `shootouts`.
3. **Penghapusan Duplikat**: Menghapus (*drop duplicates*) 82 baris data ganda pada tabel `goalscorers`.