## Data Cleaning
Tujuan: Membersihkan dan menyiapkan data sebelum digunakan.

## 1. Loading

Pertama, kita perlu mengambil data.

In [2]:
import pandas as pd

In [3]:
results = pd.read_csv("../data/raw/results.csv")
former_names = pd.read_csv("../data/raw/former_names.csv")
goalscorers = pd.read_csv("../data/raw/goalscorers.csv")
shootouts = pd.read_csv("../data/raw/shootouts.csv")

## 2. Informasi Umum Data

Kemudian, kita akan melihat beberapa informasi umum dari tabel data.

### 2.1 Tabel Results

Kita akan mengecek tabel `results`.

In [4]:
# BENTUK TABEL
results.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False


In [5]:
# INFORMASI UMUM
results.info()

<class 'pandas.DataFrame'>
RangeIndex: 49477 entries, 0 to 49476
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   date        49477 non-null  str    
 1   home_team   49477 non-null  str    
 2   away_team   49477 non-null  str    
 3   home_score  49433 non-null  float64
 4   away_score  49433 non-null  float64
 5   tournament  49477 non-null  str    
 6   city        49477 non-null  str    
 7   country     49477 non-null  str    
 8   neutral     49477 non-null  bool   
dtypes: bool(1), float64(2), str(6)
memory usage: 3.1 MB


Tipe data terlihat normal selain kolom `date`. Kolom `date` masih mempunyai format string, sehingga harus diubah nanti.

In [6]:
# MISSING VALUE
results.isna().sum()

date           0
home_team      0
away_team      0
home_score    44
away_score    44
tournament     0
city           0
country        0
neutral        0
dtype: int64

Tampaknya terdapat data kosong dengan rincian berikut:
- `home_score` : 44 data kosong
- `away_score` : 44 data kosong

In [7]:
# DUPLIKAT
results.duplicated().sum()

np.int64(0)

### 2.2 Tabel Former Names

In [8]:
# BENTUK TABEL
former_names.head()

,current,former,start_date,end_date
0,Benin,Dahomey,1959-11-08,1975-11-30
1,Burkina Faso,Upper Volta,1960-04-14,1984-08-04
2,Curaçao,Netherlands Antilles,1957-03-03,2010-10-10
3,Czechoslovakia,Bohemia,1903-04-05,1919-01-01
4,Czechoslovakia,Bohemia and Moravia,1939-01-01,1945-05-01


In [9]:
# INFORMASI UMUM
former_names.info()

<class 'pandas.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   current     36 non-null     str  
 1   former      36 non-null     str  
 2   start_date  36 non-null     str  
 3   end_date    36 non-null     str  
dtypes: str(4)
memory usage: 1.3 KB


Kasus yang sama dengan tabel `results`, tabel ini memiliki tanggal (`start_date` dan `end_date`) dengan tipe string.

In [10]:
# MISSING VALUE
former_names.isna().sum()

current       0
former        0
start_date    0
end_date      0
dtype: int64

Tidak ada data kosong.

In [11]:
# DUPLIKAT
former_names.duplicated().sum()

np.int64(0)

Tidak ada data duplikat.

### 2.3 Tabel Goalscorers

In [12]:
# BENTUK TABEL
goalscorers.head()

,date,home_team,away_team,team,scorer,minute,own_goal,penalty
0,1916-07-02,Chile,Uruguay,Uruguay,José Piendibene,44.0,False,False
1,1916-07-02,Chile,Uruguay,Uruguay,Isabelino Gradín,55.0,False,False
2,1916-07-02,Chile,Uruguay,Uruguay,Isabelino Gradín,70.0,False,False
3,1916-07-02,Chile,Uruguay,Uruguay,José Piendibene,75.0,False,False
4,1916-07-06,Argentina,Chile,Argentina,Alberto Ohaco,2.0,False,False


In [13]:
# INFORMASI UMUM
goalscorers.info()

<class 'pandas.DataFrame'>
RangeIndex: 47690 entries, 0 to 47689
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   date       47690 non-null  str    
 1   home_team  47690 non-null  str    
 2   away_team  47690 non-null  str    
 3   team       47690 non-null  str    
 4   scorer     47642 non-null  str    
 5   minute     47434 non-null  float64
 6   own_goal   47690 non-null  bool   
 7   penalty    47690 non-null  bool   
dtypes: bool(2), float64(1), str(5)
memory usage: 2.3 MB


Masih dengan kasus yang sama dengan tabel `results`, tabel ini memiliki kolom `date` dengan tipe string.

In [14]:
# MISSING VALUE
goalscorers.isna().sum()

date           0
home_team      0
away_team      0
team           0
scorer        48
minute       256
own_goal       0
penalty        0
dtype: int64

Sepertinya terdapat banyak data kosong pada beberapa kolom.
- `scorer` : 44 data kosong
- `minute` : 256 data kosong

In [15]:
# DUPLIKAT
goalscorers.duplicated().sum()

np.int64(82)

Ternyata terdapat 82 data duplikat pada tabel `goalscorers`.

### 2.4 Tabel Shootouts

In [16]:
# BENTUK TABEL
shootouts.head()

,date,home_team,away_team,winner,first_shooter
0,1967-08-22,India,Taiwan,Taiwan,NaN
1,1971-11-14,South Korea,Vietnam Republic,South Korea,NaN
2,1972-05-07,South Korea,Iraq,Iraq,NaN
3,1972-05-17,Thailand,South Korea,South Korea,NaN
4,1972-05-19,Thailand,Cambodia,Thailand,NaN


In [17]:
# INFORMASI UMUM
shootouts.info()

<class 'pandas.DataFrame'>
RangeIndex: 678 entries, 0 to 677
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           678 non-null    str  
 1   home_team      678 non-null    str  
 2   away_team      678 non-null    str  
 3   winner         678 non-null    str  
 4   first_shooter  256 non-null    str  
dtypes: str(5)
memory usage: 26.6 KB


Tabel ini juga memiliki kolom `date` dengan tipe string.

In [18]:
# MISSING VALUE
shootouts.isna().sum()

date               0
home_team          0
away_team          0
winner             0
first_shooter    422
dtype: int64

Terdapat 422 data kosong pada kolom `first_shooter`.

In [19]:
# DUPLIKAT
shootouts.duplicated().sum()

np.int64(0)

Tidak ada data duplikat.

### 2.5 Insight

- Pada tabel `results`, kolom `date` masih bertipe string dan perlu dikonversi menjadi datetime. Ditemukan 44 data kosong pada kolom `home_score` dan `away_score` yang memerlukan investigasi lebih lanjut untuk mengetahui penyebabnya.
- Pada tabel `former_names`, kolom `start_date` dan `end_date` masih bertipe string dan perlu dikonversi menjadi datetime. Selain itu, tidak ditemukan missing values maupun data duplikat.
- Pada tabel `goalscorers`, kolom `date` perlu dikonversi menjadi datetime. Ditemukan missing values pada kolom `scorer` dan `minute` yang perlu dianalisis lebih lanjut untuk memahami karakteristik data historis. Selain itu, terdapat 82 baris duplikat yang perlu diperiksa sebelum diputuskan untuk dihapus.
- Pada tabel `shootouts`, kolom `date` masih bertipe string dan perlu dikonversi menjadi datetime. Ditemukan missing values pada kolom `first_shooter`, sehingga perlu dilakukan investigasi untuk menentukan relevansinya terhadap analisis dan modelling.

#### Action Items

1. Mengonversi seluruh kolom tanggal (`date`, `start_date`, `end_date`) menjadi tipe data datetime.
2. Menginvestigasi penyebab missing values pada setiap tabel sebelum menentukan strategi penanganan yang sesuai.
3. Menginvestigasi 82 baris duplikat pada tabel `goalscorers` sebelum melakukan penghapusan.
4. Mendokumentasikan seluruh keputusan pembersihan data agar proses preprocessing dapat direproduksi dengan konsisten.

## 3. Investigasi
Sebelum memulai pembersihan, kita akan menjalankan investigasi missing value dan data duplikat seusai rencana di action items pada insight bagian **2. Informasi Umum Data**.

### 3.1 Tabel Results

Catatan: Terdapat 44 data kosong pada kolom `home_score` dan `away_score`.

In [20]:
results[
    results["home_score"].isna()
]

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
49433,2026-06-19,Scotland,Morocco,NaN,NaN,FIFA World Cup,Foxborough,United States,True
49434,2026-06-19,Brazil,Haiti,NaN,NaN,FIFA World Cup,Philadelphia,United States,True
49435,2026-06-19,United States,Australia,NaN,NaN,FIFA World Cup,Seattle,United States,False
49436,2026-06-19,Turkey,Paraguay,NaN,NaN,FIFA World Cup,Santa Clara,United States,True
49437,2026-06-20,Germany,Ivory Coast,NaN,NaN,FIFA World Cup,Toronto,Canada,True
49438,2026-06-20,Ecuador,Curaçao,NaN,NaN,FIFA World Cup,Kansas City,United States,True
49439,2026-06-20,Netherlands,Sweden,NaN,NaN,FIFA World Cup,Houston,United States,True
49440,2026-06-20,Tunisia,Japan,NaN,NaN,FIFA World Cup,Guadalupe,Mexico,True
49441,2026-06-21,Belgium,Iran,NaN,NaN,FIFA World Cup,Inglewood,United States,True
49442,2026-06-21,New Zealand,Egypt,NaN,NaN,FIFA World Cup,Vancouver,Canada,True


In [21]:
results.iloc[49429:49434]

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
49429,2026-06-18,Czech Republic,South Africa,1.0,1.0,FIFA World Cup,Atlanta,United States,True
49430,2026-06-18,Mexico,South Korea,1.0,0.0,FIFA World Cup,Zapopan,Mexico,False
49431,2026-06-18,Switzerland,Bosnia and Herzegovina,4.0,1.0,FIFA World Cup,Inglewood,United States,True
49432,2026-06-18,Canada,Qatar,6.0,0.0,FIFA World Cup,Vancouver,Canada,False
49433,2026-06-19,Scotland,Morocco,NaN,NaN,FIFA World Cup,Foxborough,United States,True


#### Temuan Investigasi

Kita bisa melihat pada tabel data yang kosong dan kita langsung tahu kenapa skor masih kosong/NaN. Ternyata, ini adalah pertandingan FIFA World Cup 2026, yang dimana sudah dijadwalkan namun belum dilaksanakan. (Catatan penting bahwa author mengambil dataset ini pada tanggal 18 Juni 2026). Sehingga pertandingan yang dilakukan setelahnya (mulai 19 Juni) belum memiliki data update hasil pertandingan.

### 3.2 Tabel Goalscorers

Catatan: Terdapat 42 baris kolom `scorer` kosong, 256 baris kolom `minutes` kosong, dan 82 data duplikat.

- Kolom Scorer

In [ ]:
goalscorers[
    goalscorers["scorer"].isna()
]


,date,home_team,away_team,team,scorer,minute,own_goal,penalty
8697,1980-02-24,Vanuatu,Papua New Guinea,Papua New Guinea,NaN,NaN,False,False
8698,1980-02-24,Vanuatu,Papua New Guinea,Papua New Guinea,NaN,NaN,False,False
8699,1980-02-24,Vanuatu,Papua New Guinea,Papua New Guinea,NaN,NaN,False,False
8700,1980-02-24,Vanuatu,Papua New Guinea,Papua New Guinea,NaN,NaN,False,False
8701,1980-02-24,Vanuatu,Papua New Guinea,Vanuatu,NaN,NaN,False,False
8702,1980-02-24,Vanuatu,Papua New Guinea,Vanuatu,NaN,NaN,False,False
8703,1980-02-24,Vanuatu,Papua New Guinea,Vanuatu,NaN,NaN,False,False
8704,1980-02-25,Fiji,Solomon Islands,Fiji,NaN,NaN,False,False
8705,1980-02-25,Fiji,Solomon Islands,Fiji,NaN,NaN,False,False
8706,1980-02-25,Fiji,Solomon Islands,Fiji,NaN,NaN,False,False


#### Temuan Investigasi

Terdapat beberapa pertandingan dengan scorer hilang ini:
1. Vanuatu vs Papua New Guinea (1980-02-24)
2. Fiji vs Solomon Islands (1980-02-25)
3. New Caledonia vs Vanuatu (1980-02-26)
4. Solomon Island vs Tahiti (1980-02-27)
5. New Caledonia vs Papua New Guinea (1980-02-28)
6. Fiji vs Tahiti (1980-02-29)

---

Tampak seperti pertandingan 1 grup yang saling bertemu. Coba kita cari salah satu pertandingan diatas pada tabel results.

In [28]:
search_data = {
    "home_team": ["Vanuatu", "Fiji", "New Caledonia", "Solomon Islands", "New Caledonia", "Fiji"],
    "away_team": ["Papua New Guinea", "Solomon Islands", "Vanuatu", "Tahiti", "Papua New Guinea", "Tahiti"],
    "date": ["1980-02-24", "1980-02-25", "1980-02-26", "1980-02-27", "1980-02-28", "1980-02-29"]
}
df_cari = pd.DataFrame(search_data)


df_cari["date"] = pd.to_datetime(df_cari["date"])
results["date"] = pd.to_datetime(results["date"])

tabel_terpilih = pd.merge(results, df_cari, on=["home_team", "away_team", "date"], how="inner")
tabel_terpilih


,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1980-02-24,Vanuatu,Papua New Guinea,3.0,4.0,Oceania Nations Cup,Nouméa,New Caledonia,True
1,1980-02-25,Fiji,Solomon Islands,3.0,1.0,Oceania Nations Cup,Nouméa,New Caledonia,True
2,1980-02-26,New Caledonia,Vanuatu,4.0,3.0,Oceania Nations Cup,Nouméa,New Caledonia,False
3,1980-02-27,Solomon Islands,Tahiti,1.0,12.0,Oceania Nations Cup,Nouméa,New Caledonia,True
4,1980-02-28,New Caledonia,Papua New Guinea,8.0,0.0,Oceania Nations Cup,Nouméa,New Caledonia,False
5,1980-02-29,Fiji,Tahiti,3.0,6.0,Oceania Nations Cup,Nouméa,New Caledonia,True


Bisa dilihat bahwa ini adalah turnamen Oceania Nations Cup. Terlihat pula disini terdapat skor tertera. Pertanyaannya, kenapa pencetak gol dan menit kosong?

- Kolom Minute

In [34]:
goalscorers[goalscorers["minute"].isna()].iloc[[*range(5), *range(-5, 0)]]
# ambil 5 terawal dan terakhir

,date,home_team,away_team,team,scorer,minute,own_goal,penalty
3347,1960-10-16,Taiwan,Vietnam Republic,Taiwan,Yiu Cheuk Yin,NaN,False,False
4059,1963-11-26,Ghana,Ethiopia,Ghana,Edward Acquah,NaN,False,False
4060,1963-11-26,Ghana,Ethiopia,Ghana,Edward Acquah,NaN,False,False
4063,1963-11-28,Ethiopia,Tunisia,Ethiopia,Mengistu Worku,NaN,False,False
4064,1963-11-28,Ethiopia,Tunisia,Ethiopia,Mengistu Worku,NaN,False,False
16812,1997-03-27,Saudi Arabia,Bangladesh,Saudi Arabia,Abdullah Al-Dosari,NaN,False,False
16838,1997-03-29,Taiwan,Bangladesh,Taiwan,Hsu Te Ming,NaN,False,False
16839,1997-03-29,Taiwan,Bangladesh,Bangladesh,Alfaz Ahmed,NaN,False,False
16840,1997-03-29,Taiwan,Bangladesh,Bangladesh,Imtiaz Ahmed Nakib,NaN,False,False
16849,1997-03-31,Bangladesh,Malaysia,Malaysia,Zainal Abidin Hassan,NaN,False,False


#### Temuan Investigasi

Terdapat pula 256 baris dimana meski punya data pencetak gol atau tidak, tidak ada data menit terjadinya gol.

In [32]:
goalscorers["minute"].isna().mean()*100

np.float64(0.5368001677500525)

- Duplikat

In [40]:
goalscorers[goalscorers.duplicated(keep=False)].iloc[[*range(5), *range(-5, 0)]]

,date,home_team,away_team,team,scorer,minute,own_goal,penalty
4059,1963-11-26,Ghana,Ethiopia,Ghana,Edward Acquah,NaN,False,False
4060,1963-11-26,Ghana,Ethiopia,Ghana,Edward Acquah,NaN,False,False
4063,1963-11-28,Ethiopia,Tunisia,Ethiopia,Mengistu Worku,NaN,False,False
4064,1963-11-28,Ethiopia,Tunisia,Ethiopia,Mengistu Worku,NaN,False,False
4067,1963-11-28,Nigeria,Sudan,Sudan,Nasr Eddin Abbas,NaN,False,False
41302,2021-09-05,San Marino,Poland,Poland,Adam Buksa,90.0,False,False
41775,2021-10-12,Syria,Lebanon,Lebanon,Mohamad Kdouh,45.0,False,False
41776,2021-10-12,Syria,Lebanon,Lebanon,Mohamad Kdouh,45.0,False,False
42832,2022-09-25,Moldova,Liechtenstein,Moldova,Victor Stînă,90.0,False,False
42833,2022-09-25,Moldova,Liechtenstein,Moldova,Victor Stînă,90.0,False,False


#### Temuan Investigasi
- Saya coba mencari pada pertandingan Syria vs Lebanon, ternyata ini adalah pertandingan 2022 FIFA World Cup qualification dan Mohamad Kdouh mencetak gol pada tambahan waktu sebelum jeda pertengahan. Namun, data mencatat pada menit 45, karena gol terjadi pada 45+1' dan 45+2'.
- Untuk memvalidasi, saya coba mencari pertandingan antara Moldova dengan Liechtenstein. Ternyata hal ini juga terjadi pada pertandingan UEFA Nations League D ini, Victor Stînă mencetak gol pada 90+2' dan 90+4'.
- Investigasi terhadap data duplikat menunjukkan bahwa beberapa baris identik berasal dari dua gol berbeda yang sama-sama terjadi pada injury time (misalnya 45+1' dan 45+2'), namun keduanya dicatat sebagai menit 45. Oleh karena itu, data duplikat ini tidak selalu merupakan kesalahan pencatatan dan memerlukan penanganan khusus.

### 3.3 Tabel Shootouts
Catatan: Terdapat 422 data kosong pada kolom `first_shooter`.

In [41]:
shootouts["first_shooter"].isna().mean()*100

np.float64(62.24188790560472)

#### Temuan Investigasi
Kolom ini memang hampir sepenuhnya kosong, namun jika kita analisis pada sisi tujuan penelitian ini, kita hampir tidak membutuhkan kolom ini. Kita bisa pertimbangkan untuk menghapus kolom ini.

### 3.4 Insight

| Masalah | Hasil Investigasi | Keputusan | Alasan |
| :--- | :--- | :--- | :--- |
| Missing `home_score` & `away_score` | 44 pertandingan merupakan jadwal FIFA World Cup 2026 yang belum dimainkan sehingga skor belum tersedia. | Hapus 44 baris tersebut. | Target (`home_score` dan `away_score`) belum diketahui sehingga tidak dapat digunakan untuk pelatihan model. |
| Missing `scorer` | Terjadi pada beberapa pertandingan Oceania Nations Cup 1980. Hasil pertandingan tersedia, namun informasi pencetak gol tidak terdokumentasi. | Pertahankan. | Tidak memengaruhi dataset utama (`results`) yang digunakan untuk prediksi hasil pertandingan. |
| Missing `minute` | Beberapa pertandingan historis tidak memiliki informasi menit terjadinya gol. | Pertahankan. | Kolom ini tidak digunakan pada Phase 1 sehingga tidak perlu dilakukan imputasi. |
| Data duplikat `goalscorers` | Ditemukan kasus injury time (misalnya 45+1' dan 45+2') yang sama-sama dicatat sebagai menit 45 sehingga menghasilkan baris identik. | Investigasi lanjutan sebelum penghapusan. | Belum semua duplikat dapat dianggap sebagai kesalahan pencatatan. |
| Missing `first_shooter` | Sebagian besar nilai kosong karena informasi penendang pertama tidak selalu dicatat. | Pertimbangkan menghapus kolom. | Tidak relevan dengan tujuan penelitian pada project ini. |

## 4. Kesimpulan Akhir dan Rencana Eksekusi

Berdasarkan seluruh tahapan pengecekan **Informasi Umum Data** dan **Investigasi** mendalam yang telah dilakukan, kita kini memiliki pemahaman yang utuh mengenai kondisi awal dataset. Secara keseluruhan, dataset ini berkualitas baik, namun memiliki beberapa karakteristik unik, anomali historis, dan data masa depan yang wajar ditemui pada *real-world data*.

Tujuan utama kita adalah menyiapkan data untuk pemodelan prediksi hasil pertandingan. Oleh karena itu, berikut adalah keputusan final atau *Action Plan* yang akan dieksekusi pada proses *Data Cleaning* sesungguhnya:

**A. Standardisasi Format**
* Mengonversi seluruh kolom yang memuat informasi waktu (`date` pada tabel `results`, `goalscorers`, dan `shootouts`; serta `start_date` & `end_date` pada tabel `former_names`) dari format *string* menjadi tipe data *datetime*.

**B. Penanganan Data Kosong (*Missing Values*)**
* **Tabel `results`**: Menghapus (*drop*) 44 baris pertandingan FIFA World Cup 2026. Data ini adalah jadwal masa depan yang skornya belum ada, sehingga secara absolut tidak dapat digunakan sebagai target pelatihan model.
* **Tabel `goalscorers`**: Membiarkan data kosong pada kolom `scorer` dan `minute`. Ketidaklengkapan ini murni karena rekam jejak historis pada turnamen lama (seperti Oceania Nations Cup 1980) dan tidak memengaruhi dataset utama yang akan digunakan untuk pemodelan prediksi.
* **Tabel `shootouts`**: Menghapus kolom `first_shooter` secara keseluruhan (*drop column*). Selain karena persentase data kosongnya terlalu mendominasi, fitur ini juga tidak relevan dengan ruang lingkup *modelling* kita.

**C. Penanganan Data Duplikat**
* **Tabel `goalscorers`**: Mempertahankan 82 baris yang terdeteksi sebagai duplikat. Berdasarkan investigasi, data ini merepresentasikan kejadian nyata di mana dua gol berbeda dicetak oleh pemain yang sama dalam waktu berdekatan pada masa *injury time* (misalnya 45+1' dan 45+2'), yang sayangnya sama-sama dibulatkan pencatatannya menjadi menit ke-45.

> **Catatan Penting:** Dokumentasi *insight* ini memastikan bahwa tidak ada data historis valid yang terbuang sia-sia akibat pembersihan buta (*blind dropping*). Langkah-langkah eksekusi di atas siap diimplementasikan pada tahap pembersihan data (tahap selanjutnya) agar dataset final valid, bersih, dan siap masuk ke fase *Exploratory Data Analysis* (EDA) serta pemodelan *Machine Learning*.